name: Build of html documentation

# will run in root folder devops/devops/
# and we will create the following (which will persist until next run):
# - ./docs/python #executable
# - psychopy #repo
# - devops #repo

on:
  workflow_dispatch:  # manual
    inputs:
      pp_branch:
        description: 'PsychoPy branch to build docs from'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - release
  pull_request:
    branches: [release, dev]
  push:
    branches: [release]

permissions:
  contents: write

jobs:

  build_html:

    runs-on: [windows-latest]
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: "SETUP: Install UV"
      uses: astral-sh/setup-uv@v7
      with:
        activate-environment: true

    - name: "SETUP: Select branch"
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "Manual trigger for branch: ${{ github.event.inputs.pp_branch }}"
          branch="${{ github.event.inputs.pp_branch }}"
        else
          echo "Scheduled trigger, using release branch"
          branch="release"
        fi
        # export for other steps
        echo "BRANCH=$branch" >> $GITHUB_ENV

    - name: "SETUP: Checkout psychopy"
      uses: actions/checkout@v4
      with:
        repository: psychopy/psychopy
        path: psychopy
        ref: ${{ env.BRANCH }}
  
    - name: "SETUP: Checkout psychopy-docs"
      uses: actions/checkout@v4
      with:
        repository: psychopy/psychopy-docs
        path: docs
        ref: ${{ env.BRANCH }}

    - name: "SETUP: Install psychopy and dependencies"
      working-directory: docs
      run: |
        ls
        # workaround for dukpy
        uv pip install git+https://gitlab.com/peircej/metapensiero.pj.git # includes fixes since last release
        # install psychopy depends for docs (incl sphinx extensions)
        uv pip install -e ".[tests]" ".[plugins]" --upgrade
    
    - name : "SETUP: Update alerts"
      working-directory: docs
      run: |
        echo "\n Create Alerts documentation:"
        python updateAlerts_rst.py

    - name: "HTML: Sphinx build html"
      working-directory: docs
      run: |
        sphinx-build -b html source build/html

    - name: "PDF: Sphinx build latex"
      working-directory: docs
      run: |
        sphinx-build -b latex source build/latex

    - name: "PDF: Cache Tectonic files"
      uses: actions/cache@v5
      with:
        path: ~/.cache/Tectonic
        key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-tectonic-
    - name: "PDF: Set up Tectonic"
      uses: wtfjoke/setup-tectonic@v4
    - name: "PDF: Build PDF with Tectonic"
      working-directory: docs
      run: |
        tectonic build/latex/PsychoPyManual.tex --outdir build/html
    - name: "DEBUG: Upload docs as artifact"
      uses: actions/upload-artifact@v6
      with:
        name: psychopy-docs
        path: docs/build/html
    - name: "DEBUG: Upload psychopyManual.tex as artifact"
      uses: actions/upload-artifact@v6
      with:
        name: PsychoPyManual.tex
        path: docs/build/latex/PsychoPyManual.tex
    # Publish to gh-pages branch
    - name: "PUBLISH: Add files to a commit"
      working-directory: docs
      run: |
        # skip jekyll build
        echo "" > build/html/.nojekyll
        # # copy the pdf to the docs/build/html
        # cp build/latex/PsychopyManual.pdf build/html/PsychoPyManual.pdf  # note the change to capital P!
        # commit all files in the docs folder (including the new pdf)
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add build/html
        git commit --all -m "sys: Build documentation"
    - name: "PUBLISH: Push to gh-pages branch"
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        